### ISSUE TITLE
Let users to create aliases in .lprofile

### ISSUE THREAD

**Issue by kyrgyz** [ghantoos/lshell#10]
Is it possible to let the users to create their own aliases by themselves? For example, in bash it is possible to define aliases in .bash_profile or .bash_aliases file. Lshell could implement something like that and let users to define their aliases in, let's say, .lprofile file.

BTW, is it possible to load new config settings without logging out from the session like it is done in normal SSH: source .bash_profile?

**Comment by autogun** [comment]
User aliases is a really wanted feature!
Hope to see this sometime.

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. There is no upper limit to group within lshell. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
