### ISSUE TITLE
comand failed when arguments has the forbidden keywords

### ISSUE THREAD

**Issue by jenningsloy318** [ghantoos/lshell#121]
I encountered a issue, we set the 'rm' command   forbidden , when we issued command which contain "rm", will be kicked off.

$ cd rma_push_status
*** forbidden syntax  -> "cd rma_push_status"

**Comment by ghantoos** [comment]
The "forbidden" variable contains forbidden characters/strings, which will match your file name in this case.

Why do you need to put it in the "forbidden", you can just not add it to the "allowed". All the other commands are automatically forbidden.

Does this help?

**Comment by jenningsloy318** [comment]
You mean that if it is not in allowed list, it can be forbidden to execute?
Thank you, I will have a try.

**Comment by ghantoos** [comment]
Yes, if a command is not in the allowed list, then it is forbidden.

**Comment by jenningsloy318** [comment]
Tested it. it is working now, thanks.

**Comment by tealord** [comment]
In my case '&' needs to be a parameter and since it is in default configuration forbidden my command fails:

`user:~$ echo foo`
`foo`
`user:~$ echo 'foo'`
`foo`
`user:~$ echo 'foo&'`
`*** forbidden syntax -> "echo 'foo&'"`
`*** You have 98 warning(s) left, before getting kicked out.`
`This incident has been reported.`

Removing '&' from the forbidden character list does not help because it is interpreted to execute the next command, even if its single quoted. Do you have a solution for this? Thank you very much!
