### ISSUE TITLE
xontrib xutil for xonsh

### ISSUE THREAD

**Issue by den-run-ai** [ghantoos/lshell#139]
Hey, lshell folks! What is your opinion on contributing xonsh plugin which uses lshell instead of bash?

https://github.com/scopatz/xonsh/issues/966

cc: @adqm @scopatz

**Comment by ghantoos** [comment]
Hey @denfromufa,

xonsh is quite an interesting project. I am conding/maintaining lshell by myself, and have had some major contributors in the past few years.

Unfortunately I haven't got enough time (today) to dive into another project. Even though xonsh seems to be quite an interesting project, I'm afraid I won't be able to participate. 

Unless some of you folks work with me on some pull requests to enhance lshell itself? :)

**Comment by ghantoos** [comment]
btw, thanks a lot for your interest in lshell, I am sure that if we are able to work together, this might be very useful for the project! ;)

**Comment by denfromufa** [comment]
GPL prevents any work on integrating lshell from xonsh side

**Comment by scopatz** [comment]
Well, we could add to lshell a xontrib (http://xon.sh/xontribs.html) if you would be interested.  But I think the point that @denfromufa is making is that we couldn't just incorporate lshell into xonsh because of the licence.  That said, I am glad that there is some will to potentially work together.  lshell is a cool project and it would be nice to mesh it up optionally with xonsh if we can.
