### ISSUE TITLE
Feature: Unable to allow one-liners that contain pipe character

### ISSUE THREAD

**Issue by hendralinux** [ghantoos/lshell#163]
I'm planning to use lshell to restrict the netdump user in RHEL 7. When setting up kdump, the `kdumpctl propagate` will execute the following command:

`exec sh -c 'umask 077; mkdir -p .ssh && cat >> .ssh/authorized_keys || exit 1; if type restorecon >/dev/null 2>&1; then restorecon -F .ssh .ssh/authorized_keys; fi'"`

and failed with the `*** forbidden char/command over SSH:` error, even after allowing everything used by that command in the lshell.conf. 

Any suggestion on how to make this work?

**Comment by acataluddi** [comment]
Hello @hendrahendra,
by the `lshell` configuration you can disable some chars like in the following example:

```python
[default]
allowed         : ['ls','pwd']
forbidden       : [';', '&', '|'] 
```

Could it be that you restricted the pipe `|` char in your `/etc/lshell.conf`?

Regards,
Adriano

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I tried to reproduced but wasn't able to. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!

**Comment by ghantoos** [comment]
This should theoretically work now - haven't tested.
