### ISSUE TITLE
Bug: Limit on number of groups

### ISSUE THREAD

**Issue by fatalkill3r** [ghantoos/lshell#189]
Hi

It seems that lshell experiences problem when a user belongs to more than 10 groups. sudo permissions start misbehaving. Is there any type of upper limit on number of groups a user can belong to?

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. There is no upper limit to group within lshell. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
