### ISSUE TITLE
Bug: lshell user exit from current shell if use tail on some file and exit via ctrl+c command

### ISSUE THREAD

**Issue by adg333221** [ghantoos/lshell#190]
on remote server i use lshell for restricted user to run some commands on there
while tailing some log file  via **tail -f**  it goes fine but when exit from tail via ctrl+c it exit from remote shell to and take me to my local system 
this is unexpected behaviour 
i seen in lshell

**Comment by sudhirpoodar** [comment]
Hi Team,
any update on this.

**Comment by ghantoos** [comment]
I can't reproduce with the latest code. Closing the issue. Feel free to reopen if needed. Thanks!

This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
