### ISSUE TITLE
Configuration to minimize risk of shell escape

### ISSUE THREAD

**Issue by nlhooper** [ghantoos/lshell#199]
In light of the various unfixed shell escape issues (e.g. issues 147-9 & 151).  Are there any configuration changes that I can make to try to prevent a user from escaping from lshell?

Several of the exploits make use of echo and as I don't need it I have removed it from the list of allowed commands.

I am running lshell version 0.9.16 on centos which I believe is the latest version that there is a package for.

Here is an extract of my config:

allowed         : ['ls','cd','ll','su','scp']
forbidden       : [';', '&', '|','`','>','<', '$(', '${']`

**Comment by ghantoos** [comment]
This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean. We are also working on fixing the security issues. A new package will follow.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
