### ISSUE TITLE
Prevent shell execution tag in command parameters

### ISSUE THREAD

**Issue by emathias** [ghantoos/lshell#205]
For instance, if I want to allow 'echo', but prevent 'cat', how can I prevent users from doing: 

$ echo "$(cat file.txt)"

For info, the 'forbidden' config does not catch command parameters

Thanks a lot for such a nice tool! 

Best regards,

**Comment by ghantoos** [comment]
With the default config, I'm getting:
```
~$ echo "$(cat file.txt)"
*** forbidden syntax: echo "$(cat file.txt)"
```

This project has been inactive for a while, and this issue has been open for a long time without activity. I'm closing it to keep the issue tracker clean.

If this issue is still relevant to you, please feel free to reopen it or create a new one. Appreciate your understanding and support!
