### ISSUE TITLE
"cd directory && command" does not work

### ISSUE THREAD

**Issue by hostingnuggets** [ghantoos/lshell#67]
A stupid command such as:

cd /tmp && ls

does not work:

lshell: tmp && ls: No such file or directory

It looks like lshell does not see the "&&" and treats the whole string (tmp && ls) as the directory to cd into...

**Comment by ghantoos** [comment]
Actually, if the command does not start with cd, then the internal cd function isn't used. Example: ```echo 1 && cd src && ls```.

In order to make this more coherent, I have committed a patch that ignores the internal cd function, when the line contains particular symbols/tokens (e.g. pipe our semi-column).

This will make the shell work as expected when the command starts with "cd" and has more than one command. Even though the user will remain in the same directory after the command is executed.

```
ghantoos:~$ cd src/lshell/lshell; ls -l | grep cmd
-rw-r--r-- 1 ghantoos3 ghantoos3 30802 Jul  5 21:34 shellcmd.py
ghantoos:~$ 
```

The next step would be the lexer/parser. One step at a time. ;)

**Comment by xlr-8** [comment]
"The next step would be the lexer/parser. One step at a time. ;)" :+1:
